services:
  home-page:
    container_name: home-page
    build: .
    user: 1000:1000
    environment:
      - TZ=Asia/Shanghai
      - NEXT_PUBLIC_HOME_HEADER_TITLE=HOME
      - NEXT_PUBLIC_HOME_TITLE=六六の家
    volumes:
      - ./services.json:/app/services.json
      - /cloud:/cloud
      - /space:/space
    ports:
      - 3000:3000
    restart: unless-stopped
